### ISSUE TITLE
Setup steps

### ISSUE THREAD

**Issue by ruxiang05** [xfumihiro/jest-puppeteer#2]
Could you please add all the setup steps needed? 

After adding it with yarn it gives me the this error: `Cannot read property 'newPage' of undefined`.

I have also added the config file and the jest-puppeteer command in package.json

**Comment by xfumihiro** [comment]
Have you tried the "example"?
It should be working.

**Comment by ruxiang05** [comment]
I wasn't puttin the config file in the correct place, closing this.
