### ISSUE TITLE
Why is this deprecated?

### ISSUE THREAD

**Issue by NickColley** [xfumihiro/jest-puppeteer#3]
It seems like a nice idea to wrap the boilerplate.

Would you be open to me maintaining and publishing something that wraps the boilerplate?

**Comment by xfumihiro** [comment]
It's deprecated because there's [more elegant way](https://github.com/xfumihiro/jest-puppeteer-example) to achieve the same thing.

Feel free to use this code anyway you want!

**Comment by NickColley** [comment]
Thanks for the reply :)
